### PR TITLE
Added ruby, rubydev and bundler

### PR DESCRIPTION
**Pull request by denizmveli**

### CODE REVIEW

**Comment by rayh** [comment]
Might be better to just change the base image to phusion/passenger-docker - which contains ruby, node, etc.  What do you think?

**Comment by denizmveli** [comment]
Might be overkill since it includes node and python, but I don't have strong opinions.

**Comment by rayh** [comment]
Installing the default version of ruby might not be best - let's pin it to a specific version - @adriancb what method would you recommend for installing ruby?

**Comment by adriancb** [comment]
I'd just lock down the ruby version.

**Comment by denizmveli** [comment]
Can do the latest stable ? 2.3.1 ?

**Comment by rayh** [comment]
Sounds good to me

**Comment by denizmveli** [comment]
Now with pinned version !

**Comment by rayh** [comment]
I guess 1.9 is the latest that distro supports?  It'll do for now

**Comment by denizmveli** [comment]
Yep was the latest

**Pull request merged**
